---
- src: https://github.com/lukeyeager/ansible-role-hosts.git
  version: '711ba98571f068a8bc6739fa1055ac38fc931010'
  name: lukeyeager.hosts

- src: geerlingguy.ntp
  version: "1.6.3"

- src: andrewrothstein.miniconda
  version: "v5.2.6"

- src: nvidia.nvidia_driver
  version: "v1.1.2"

- src: nvidia.nvidia_docker
  version: "v1.1.1"

- src: https://github.com/NVIDIA/ansible-role-enroot.git
  verions: "v0.1.2"

- src: geerlingguy.filebeat
  version: "2.0.1"

- src: geerlingguy.logstash
  version: "4.0.0"

- src: geerlingguy.elasticsearch
  version: "3.0.1"

- src: geerlingguy.java
  version: "1.9.5"

- src: geerlingguy.kibana
  version: "3.2.1"

- src: https://github.com/DeepOps/ansible-maas.git
  name: ansible-maas
